import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.sensor': 'Skyvantage Sensor',
    'nav.solver': 'GF2 Solver',
    'nav.guidance': 'Guidance Logic',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'hero.badge': 'Software-Defined Defence',
    'hero.title': 'Skyvantage',
    'hero.subtitle': 'Asymmetric Counter-UAS and Guidance Logic. Redefining aerial defence through high-fidelity software brains.',
    'hero.explore': 'Explore Products',
    'hero.contact': 'Contact Us',
    'features.title': 'THE SKYVANTAGE PRODUCT LINE',
    'features.subtitle': "We aren't building a better drone. We are building a cheaper brain. Defence at scale through asymmetric unit economics.",
    'footer.description': 'Asymmetric Counter-UAS and Guidance Logic. Redefining the limits of aerial defence through software-defined innovation.',
    'footer.products': 'Products',
    'footer.company': 'Company',
    'footer.rights': '© 2026 Stalwart Holdings. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'about.title': 'ABOUT SKYVANTAGE',
    'about.subtitle': 'Skyvantage is at the forefront of software-defined defence. We specialise in creating asymmetric advantages through algorithmic innovation, transforming standard hardware into precision-guided systems.',
    'about.academic': 'Academic Foundation',
    'about.academic_desc': 'Our technology is rooted in rigorous academic research and mathematical validation. We collaborate with leading institutions to ensure our algorithms are at the cutting edge of RF physics and cryptanalysis.',
    'about.vision': 'Strategic Vision',
    'about.vision_desc': 'We believe in "Defence at Scale." By reducing the cost of interception to the absolute floor, we enable symmetric responses to massed asymmetric threats.',
    'about.mission': 'Our Mission',
    'about.mission_desc': 'To provide allied forces with the most cost-effective, adaptable, and lethal software-defined defence systems in the world. We are redefining the unit economics of modern warfare through the Skyvantage platform.',
    'contact.title': 'CONTACT US',
    'contact.subtitle': 'Have questions about our software-defined defence solutions? Our team is ready to provide technical briefings and TRL4 validation reports.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.message': 'Brief Message',
    'contact.send': 'Send Message',
    'sensor.title': 'SKYVANTAGE SENSOR',
    'sensor.subtitle': 'Universal Software Defined Terminal Guidance Sensor Suite for High Speed Counter UAS. A completely self-contained edge compute module for seamless integration.',
    'sensor.cost': 'Unit Cost',
    'sensor.speed': 'Tracking Speed',
    'sensor.edge_compute': 'Edge Compute',
    'sensor.edge_compute_desc': 'Powered by a UK-manufactured Raspberry Pi 5 module and dual-channel phase coherent SDR.',
    'sensor.direct_mount': 'Direct Mount',
    'sensor.direct_mount_desc': 'Antennas attached directly to the radio chassis to eliminate phase delay and signal loss.',
    'sensor.mavlink': 'MAVLink Integration',
    'sensor.mavlink_desc': 'Universal serial bus connection for power and high-speed data conduit for autopilot commands.',
    'sensor.tech_overview': 'Technical Overview',
    'sensor.tech_p1': 'The Skyvantage Sensor functions as a completely self-contained edge compute module enabling seamless integration onto any existing host interceptor with a maximum take-off weight under 25 kilogrammes.',
    'sensor.tech_p2': 'The architecture connects to standard flight controllers via universal serial bus to issue MAVLink commands, commanding the host vehicle to manoeuvre to within 3 metres of an agile target at combined closing speeds of up to Mach 1.',
    'sensor.specs': 'Key Specifications',
    'sensor.compute': 'Compute',
    'sensor.radio': 'Radio',
    'sensor.antennas': 'Antennas',
    'sensor.interface': 'Interface',
    'sensor.supply_chain': 'Supply Chain',
    'sensor.trl4': 'TRL4 Validation Data',
    'sensor.trl4_desc': 'High-fidelity sensor telemetry captured during Mach 1.2 simulated engagement.',
    'sensor.disclaimer': 'INDICATIVE ILLUSTRATION - THE ACTUAL PRODUCT MAY LOOK DIFFERENT',
    'solver.title': 'GF2 SOLVER',
    'solver.subtitle': 'Proprietary quasilinear solver for heavy NP-Complete applications. Optimised for structurally dense unique promise satisfiability problems.',
    'solver.apps': 'Industrial Applications',
    'solver.app1_title': 'Civilian UAS key recovery',
    'solver.app1_desc': 'Rapidly recovering lost encryption keys for civilian drone fleets to ensure operational continuity without hardware replacement.',
    'solver.app2_title': 'Trusted hardware verification',
    'solver.app2_desc': 'Formal verification of logic circuits to detect hardware Trojans and ensure the integrity of secure processor designs.',
    'solver.app3_title': 'Automated cryptoanalysis',
    'solver.app3_desc': 'Accelerating the analysis of cryptographic primitives through evolutionary rank augmentation in the GF(2) field.',
    'solver.app4_title': 'AI model verification',
    'solver.app4_desc': 'Ensuring the robustness and safety of neural networks by verifying complex boolean constraints within the model architecture.',
    'solver.dual_use': 'Dual Use Capability',
    'solver.dual1_title': 'Trusted Hardware Verification',
    'solver.dual1_desc': 'Providing formal proof of circuit integrity for high-assurance semiconductor manufacturing and secure enclave validation.',
    'solver.dual2_title': 'Trusted AI Integrity',
    'solver.dual2_desc': 'Verifying the safety constraints of autonomous systems and neural networks to prevent adversarial exploitation in civilian infrastructure.',
    'solver.dual3_title': 'Civilian Fleet Management',
    'solver.dual3_desc': 'Enabling secure recovery and management of large-scale commercial UAS fleets through advanced cryptographic key restoration.',
    'solver.dual4_title': 'Automated Security Auditing',
    'solver.dual4_desc': 'Streamlining the audit of complex software systems by resolving underlying satisfiability problems in record time.',
    'solver.math': 'Mathematical Validation',
    'solver.poly_time': 'Polynomial Time',
    'solver.unique_recovery': 'Unique Solution Recovery',
    'solver.field_opt': 'Field Optimisation',
    'solver.math_summary': 'Our proprietary Evolutionary Rank Augmentation algorithm provides a polynomial-time solution for structurally dense unique promise satisfiability problems.',
    'solver.finite_field': 'Finite Field Algebra',
    'solver.complexity_res': 'Complexity Resolution',
    'solver.complexity_res_desc': 'Solves average NP-Complete problems in polynomial time when there is a unique solution',
    'solver.val_summary': 'Validation Summary',
    'solver.val_desc': 'The solver has been rigorously validated through formal complexity analysis, demonstrating expected polynomial time behaviour on random Circuit-USAT instances. This framework transforms Boolean constraints into sparse systems of equations, treating the search as a stochastic rank augmentation process.',
    'guidance.title': 'SKYVANTAGE LOGIC',
    'guidance.subtitle': 'Software-defined terminal guidance that transforms any allied drone into a precision kinetic weapon. Independent of GNSS and optical sensors.',
    'guidance.delivery': 'Delivery Model',
    'guidance.saas': 'Software as a Service (SaaS)',
    'guidance.scenarios': 'Operating scenarios validated in high-fidelity simulation.',
    'guidance.assertions': 'Mathematical assertions verified during TRL4 testing.',
    'guidance.latency': 'Latency',
    'guidance.fleet': 'Fleet-Wide Retrofitting',
    'guidance.fleet_desc': 'The engineering approach explicitly removes the need to procure expensive new interceptor fleets and enables military operators to retrofit their existing inventory of low cost allied drones.',
    'guidance.feat1': 'Low-latency C++ implementation for edge compute',
    'guidance.feat2': 'Compatible with MAVLink protocol standards',
    'guidance.feat3': 'Dynamic physical baseline configurability',
    'guidance.feat4': 'GNSS-independent terminal guidance',
    'guidance.continuous': 'Continuous Threat Resolution',
    'guidance.continuous_desc': 'The system relies on a SaaS delivery model to ensure the terminal guidance capabilities remain continuously effective against rapidly evolving adversarial threats. Over-the-air firmware updates guarantee adaptation to new frequency hopping protocols.',
    'guidance.quote': '"We aren\'t building a better drone. We are building a cheaper brain."',
    'home.tactical': 'TACTICAL VALIDATION',
    'home.tactical_desc': 'Rigorous C++ simulation framework modelling real-world RF physics and hardware drift.',
    'home.scenario04': 'Terrain Masking Re-acquisition',
    'home.scenario12': 'High-Speed Signal Tracking',
    'home.scenario07': 'Non-Kinetic Disarm Injection',
    'home.secure': 'SECURE YOUR AIRSPACE',
    'home.secure_desc': 'Join the next generation of software-defined defence. Request a full technical briefing and TRL4 validation report.',
    'features.sensor_desc': 'Universal Software Defined Terminal Guidance Sensor Suite. A completely self-contained edge compute module for high-speed Counter-UAS.',
    'features.solver_desc': 'Proprietary quasilinear solver for heavy NP-Complete applications. Optimised for industrial key recovery and hardware verification.',
    'features.guidance_desc': 'Software-defined guidance logic capable of tracking high-subsonic loitering munitions on sub-£500 processors.',
    'features.learn_more': 'Learn More',
    'hero.intercept_speed': 'Intercept Speed',
    'hero.target_class': 'Target Class',
    'hero.unit_cost': 'Unit Cost',
    'hero.seeker': 'Seeker',
    'about.leadership': 'Leadership',
    'about.fabio_title': 'Principal Investigator / CEO',
    'about.fabio_bio': 'Dr Dias will lead the digital signal processing and algorithmic development for the sensor suite, leveraging his extensive background in mathematical modelling to direct the edge computing and software implementations. As the Programme Director of the FinTech and Policy MSc at the University of Surrey and the CEO of Skyvantage, he holds a STEM PhD from University College London. He brings over two decades of experience bridging applied computer science, software innovation, and complex algorithmic design from senior roles at major financial institutions.',
    'about.alex_title': 'C++ Software Engineer',
    'about.alex_bio': 'Alexander will serve as the lead C++ software engineer, responsible for porting the complex digital signal processing algorithms and phase interferometry mathematics into highly optimised, low-latency firmware for the edge compute module. Based in London, he is a software developer with a background in building robust, high-performance systems. His programming expertise will be crucial for translating theoretical mathematical models into executable C++ code that operates efficiently within the strict processing and memory constraints of the Raspberry Pi hardware.',
  },
  pt: {
    'nav.sensor': 'Sensor Skyvantage',
    'nav.solver': 'Solver GF2',
    'nav.guidance': 'Lógica de Orientação',
    'nav.about': 'Sobre Nós',
    'nav.contact': 'Contato',
    'hero.badge': 'Defesa Definida por Software',
    'hero.title': 'Skyvantage',
    'hero.subtitle': 'Contra-UAS Assimétrico e Lógica de Orientação. Redefinindo a defesa aérea através de cérebros de software de alta fidelidade.',
    'hero.explore': 'Explorar Produtos',
    'hero.contact': 'Contate-nos',
    'features.title': 'A LINHA DE PRODUTOS SKYVANTAGE',
    'features.subtitle': 'Não estamos construindo um drone melhor. Estamos construindo um cérebro mais barato. Defesa em escala através de economia unitária assimétrica.',
    'footer.description': 'Contra-UAS Assimétrico e Lógica de Orientação. Redefinindo os limites da defesa aérea através da inovação definida por software.',
    'footer.products': 'Produtos',
    'footer.company': 'Empresa',
    'footer.rights': '© 2026 Stalwart Holdings. Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'about.title': 'SOBRE A SKYVANTAGE',
    'about.subtitle': 'A Skyvantage está na vanguarda da defesa definida por software. Especializamo-nos em criar vantagens assimétricas através de inovação algorítmica, transformando hardware padrão em sistemas guiados de precisão.',
    'about.academic': 'Fundação Acadêmica',
    'about.academic_desc': 'Nossa tecnologia está enraizada em pesquisa acadêmica rigorosa e validação matemática. Colaboramos com instituições líderes para garantir que nossos algoritmos estejam na vanguarda da física de RF e criptoanálise.',
    'about.vision': 'Visão Estratégica',
    'about.vision_desc': 'Acreditamos na "Defesa em Escala". Ao reduzir o custo de interceptação ao mínimo absoluto, permitimos respostas simétricas a ameaças assimétricas em massa.',
    'about.mission': 'Nossa Missão',
    'about.mission_desc': 'Fornecer às forças aliadas os sistemas de defesa definidos por software mais econômicos, adaptáveis e letais do mundo. Estamos redefinindo a economia unitária da guerra moderna através da plataforma Skyvantage.',
    'contact.title': 'CONTATE-NOS',
    'contact.subtitle': 'Tem perguntas sobre nossas soluções de defesa definidas por software? Nossa equipe está pronta para fornecer briefings técnicos e relatórios de validação TRL4.',
    'contact.name': 'Nome',
    'contact.email': 'E-mail',
    'contact.phone': 'Telefone',
    'contact.location': 'Localização',
    'contact.message': 'Mensagem Breve',
    'contact.send': 'Enviar Mensagem',
    'sensor.title': 'SENSOR SKYVANTAGE',
    'sensor.subtitle': 'Conjunto de Sensores de Orientação Terminal Definido por Software Universal para Contra-UAS de Alta Velocidade. Um módulo de computação de borda completamente autônomo para integração perfeita.',
    'sensor.cost': 'Custo Unitário',
    'sensor.speed': 'Velocidade de Rastreamento',
    'sensor.edge_compute': 'Computação de Borda',
    'sensor.edge_compute_desc': 'Equipado com um módulo Raspberry Pi 5 fabricado no Reino Unido e SDR coerente de fase de canal duplo.',
    'sensor.direct_mount': 'Montagem Direta',
    'sensor.direct_mount_desc': 'Antenas anexadas diretamente ao chassi do rádio para eliminar o atraso de fase e a perda de sinal.',
    'sensor.mavlink': 'Integração MAVLink',
    'sensor.mavlink_desc': 'Conexão de barramento serial universal para energia e conduíte de dados de alta velocidade para comandos de piloto automático.',
    'sensor.tech_overview': 'Visão Geral Técnica',
    'sensor.tech_p1': 'O Sensor Skyvantage funciona como um módulo de computação de borda completamente autônomo, permitindo a integração perfeita em qualquer interceptor host existente com um peso máximo de decolagem inferior a 25 quilogramas.',
    'sensor.tech_p2': 'A arquitetura se conecta a controladores de voo padrão via barramento serial universal para emitir comandos MAVLink, comandando o veículo host a manobrar a até 3 metros de um alvo ágil em velocidades de fechamento combinadas de até Mach 1.',
    'sensor.specs': 'Especificações Principais',
    'sensor.compute': 'Computação',
    'sensor.radio': 'Rádio',
    'sensor.antennas': 'Antenas',
    'sensor.interface': 'Interface',
    'sensor.supply_chain': 'Cadeia de Suprimentos',
    'sensor.trl4': 'Dados de Validação TRL4',
    'sensor.trl4_desc': 'Telemetria de sensor de alta fidelidade capturada durante engajamento simulado a Mach 1.2.',
    'sensor.disclaimer': 'ILUSTRAÇÃO INDICATIVA - O PRODUTO REAL PODE SER DIFERENTE',
    'solver.title': 'SOLVER GF2',
    'solver.subtitle': 'Solver quasilinear proprietário para aplicações NP-Completas pesadas. Otimizado para problemas de satisfatibilidade de promessa única estruturalmente densos.',
    'solver.apps': 'Aplicações Industriais',
    'solver.app1_title': 'Recuperação de chaves UAS civis',
    'solver.app1_desc': 'Recuperação rápida de chaves de criptografia perdidas para frotas de drones civis para garantir a continuidade operacional sem substituição de hardware.',
    'solver.app2_title': 'Verificação de hardware confiável',
    'solver.app2_desc': 'Verificação formal de circuitos lógicos para detectar Trojans de hardware e garantir a integridade de designs de processadores seguros.',
    'solver.app3_title': 'Criptoanálise automatizada',
    'solver.app3_desc': 'Acelerando a análise de primitivas criptográficas através do aumento de rank evolucionário no campo GF(2).',
    'solver.app4_title': 'Verificação de modelo de IA',
    'solver.app4_desc': 'Garantindo a robustez e segurança de redes neurais verificando restrições booleanas complexas na arquitetura do modelo.',
    'solver.dual_use': 'Capacidade de Uso Duplo',
    'solver.dual1_title': 'Verificação de Hardware Confiável',
    'solver.dual1_desc': 'Fornecendo prova formal de integridade de circuito para fabricação de semicondutores de alta segurança e validação de enclave seguro.',
    'solver.dual2_title': 'Integridade de IA Confiável',
    'solver.dual2_desc': 'Verificando as restrições de segurança de sistemas autônomos e redes neurais para evitar exploração adversária em infraestrutura civil.',
    'solver.dual3_title': 'Gestão de Frotas Civis',
    'solver.dual3_desc': 'Permitindo a recuperação e gestão seguras de frotas comerciais de UAS em larga escala através do restauro avançado de chaves criptográficas.',
    'solver.dual4_title': 'Auditoria de Segurança Automatizada',
    'solver.dual4_desc': 'Otimizando a auditoria de sistemas de software complexos ao resolver problemas de satisfatibilidade subjacentes em tempo recorde.',
    'solver.math': 'Validação Matemática',
    'solver.poly_time': 'Tempo Polinomial',
    'solver.unique_recovery': 'Recuperação de Solução Única',
    'solver.field_opt': 'Otimização de Campo',
    'solver.math_summary': 'Nosso algoritmo proprietário Evolutionary Rank Augmentation fornece uma solução de tempo polinomial para problemas de satisfatibilidade de promessa única estruturalmente densos.',
    'solver.finite_field': 'Álgebra de Campo Finito',
    'solver.complexity_res': 'Resolução de Complexidade',
    'solver.complexity_res_desc': 'Resolve problemas NP-Completos médios em tempo polinomial quando há uma solução única',
    'solver.val_summary': 'Resumo da Validação',
    'solver.val_desc': 'O solver foi rigorosamente validado através de análise formal de complexidade, demonstrando comportamento esperado em tempo polinomial em instâncias Circuit-USAT aleatórias. Este framework transforma restrições booleanas em sistemas esparsos de equações, tratando a pesquisa como um processo de aumento de rank estocástico.',
    'guidance.title': 'LÓGICA SKYVANTAGE',
    'guidance.subtitle': 'Orientação terminal definida por software que transforma qualquer drone aliado em uma arma cinética de precisão. Independente de GNSS e sensores ópticos.',
    'guidance.delivery': 'Modelo de Entrega',
    'guidance.saas': 'Software como Serviço (SaaS)',
    'guidance.scenarios': 'Cenários operacionais validados em simulação de alta fidelidade.',
    'guidance.assertions': 'Asserções matemáticas verificadas durante testes TRL4.',
    'guidance.latency': 'Latência',
    'guidance.fleet': 'Retroajuste em Toda a Frota',
    'guidance.fleet_desc': 'A abordagem de engenharia remove explicitamente a necessidade de adquirir novas frotas de interceptores dispendiosas e permite que os operadores militares reajustem o seu inventário existente de drones aliados de baixo custo.',
    'guidance.feat1': 'Implementação C++ de baixa latência para computação de borda',
    'guidance.feat2': 'Compatível com padrões de protocolo MAVLink',
    'guidance.feat3': 'Configurabilidade de linha de base física dinâmica',
    'guidance.feat4': 'Orientação terminal independente de GNSS',
    'guidance.continuous': 'Resolução Contínua de Ameaças',
    'guidance.continuous_desc': 'O sistema baseia-se num modelo de entrega SaaS para garantir que as capacidades de orientação terminal permanecem continuamente eficazes contra ameaças adversárias em rápida evolução. As atualizações de firmware over-the-air garantem a adaptação a novos protocolos de salto de frequência.',
    'guidance.quote': '"Não estamos construindo um drone melhor. Estamos construindo um cérebro mais barato."',
    'home.tactical': 'VALIDAÇÃO TÁTICA',
    'home.tactical_desc': 'Framework de simulação C++ rigoroso que modela física de RF e desvio de hardware do mundo real.',
    'home.scenario04': 'Reaquisição de Mascaramento de Terreno',
    'home.scenario12': 'Rastreamento de Sinal de Alta Velocidade',
    'home.scenario07': 'Injeção de Desarmamento Não Cinético',
    'home.secure': 'PROTEJA O SEU ESPAÇO AÉREO',
    'home.secure_desc': 'Junte-se à próxima geração de defesa definida por software. Solicite um briefing técnico completo e um relatório de validação TRL4.',
    'features.sensor_desc': 'Conjunto de Sensores de Orientação Terminal Definido por Software Universal. Um módulo de computação de borda completamente autônomo para Contra-UAS de alta velocidade.',
    'features.solver_desc': 'Solver quasilinear proprietário para aplicações NP-Completas pesadas. Otimizado para recuperação de chaves industriais e verificação de hardware.',
    'features.guidance_desc': 'Lógica de orientação definida por software capaz de rastrear munições loitering de alta velocidade em processadores de menos de £500.',
    'features.learn_more': 'Saiba Mais',
    'hero.intercept_speed': 'Velocidade de Interceptação',
    'hero.target_class': 'Classe do Alvo',
    'hero.unit_cost': 'Custo Unitário',
    'hero.seeker': 'Buscador',
    'about.leadership': 'Liderança',
    'about.fabio_title': 'Investigador Principal / CEO',
    'about.fabio_bio': 'O Dr. Dias liderará o processamento de sinais digitais e o desenvolvimento algorítmico do conjunto de sensores, aproveitando a sua vasta experiência em modelação matemática para dirigir as implementações de computação de borda e software. Como Diretor de Programa do Mestrado em FinTech e Política na Universidade de Surrey e CEO da Skyvantage, possui um doutorado STEM pela University College London. Traz mais de duas décadas de experiência unindo ciência da computação aplicada, inovação de software e design algorítmico complexo de cargos seniores em grandes instituições financeiras.',
    'about.alex_title': 'Engenheiro de Software C++',
    'about.alex_bio': 'Alexander servirá como o engenheiro de software C++ líder, responsável por portar os algoritmos complexos de processamento de sinais digitais e matemática de interferometria de fase em firmware altamente otimizado e de baixa latência para o módulo de computação de borda. Baseado em Londres, é um programador de software com experiência na construção de sistemas robustos e de alto desempenho. A sua experiência em programação será crucial para traduzir modelos matemáticos teóricos em código C++ executável que funciona eficientemente dentro das estritas restrições de processamento e memória do hardware Raspberry Pi.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('skyvantage_lang');
    return (saved === 'pt' || saved === 'en') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('skyvantage_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
